### ISSUE TITLE
lodash-es-4.6.0.tgz 404 error on npm install.

### ISSUE THREAD

**Issue by M1kep** [FreeCodeCamp/COM1000#54]
npm ERR! fetch failed https://registry.npmjs.org/lodash-es/-/lodash-es-4.6.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404

That error comes up a couple times and then it exits.

If I try to run npm run build it then says that it can't find webpack

**Comment by benmcmahon100** [comment]
Hi @M1kep ,
This issue is likely due to a glitch during npm install. Try deleting your node_modules folder inside COM, then run the command `npm cache clear` followed by `npm install`

**Comment by benmcmahon100** [comment]
Closing as stale and due to not being able to re-create.

Please feel free to re-open if the issue persists!
