### ISSUE TITLE
Add testing

### ISSUE THREAD

**Issue by SaintPeter** [FreeCodeCamp/COM1000#9]
_From @BerkeleyTrue on October 30, 2015 18:51_

_Copied from original issue: FreeCodeCamp/ChallengeOMatic1003#7_

**Comment by SaintPeter** [comment]
_From @terakilobyte on November 25, 2015 14:58_

Basic testing framework and initial reducer tests are in a PR against https://github.com/freecodecamp/com1000

**Comment by BerkeleyTrue** [comment]
We will be using tape.js throughout FCC
